
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8080
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/admin/**

# Product Service
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**

# Temporarily disable Config Server lookup
spring.cloud.config.enabled=false

# Temporarily disable Eureka registration/discovery
eureka.client.enabled=true

jwt.secret=3Kkq8+6S4Q7l8oBz+2u9X0cQjQvN0Zj4s9L4Gg2iW2mQv1mBqQm8GvN3k8G2tY8uQ1yT6pJ7nF5zK4vC8wR2nQ==

